apiVersion: ENC[AES256_GCM,data:84I=,iv:vqjnHPRrwlQHfvjt8JCXYaiYdZRFpbVOzgHVvoUiSgI=,tag:Hri8qJo0/4LAZ9U9cutQyw==,type:str]
kind: ENC[AES256_GCM,data:H+7RWtNb,iv:Ae0j9/PaZHWG9/BE8G3PqekxZp+VSBAHsmGKbxPKHYQ=,tag:VdoaiudVNfiodaOZXcf1tA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:X1tuun3N1CD2,iv:x3fWbfdNoa+54mM3e0XtFvPHXWpQDVYst6G2El0ND4s=,tag:DdcdyY21SAEbkeK3yx3XWQ==,type:str]
    namespace: ENC[AES256_GCM,data:XxD+qkcRNw==,iv:F+gjEt78bl8iXUxDGxLTsb9sydGjSJmzrPPmY65r+DU=,tag:37yCNVoIcqc4sq+9fFC2jg==,type:str]
type: ENC[AES256_GCM,data:mx9LRbhe,iv:JaAEo0rsMl7I/iWmpzbIHLCKbkZCVWTcUAJiqiSWkw4=,tag:RESJ1m8yMgd9jicSD7FqMg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:i7zJrpw=,iv:7+WVEFe/WaFxuRUxIduAUqFE6oB1eg3HBInAROSkp0o=,tag:08NpHIWRGGJIjsmUYZVw3w==,type:str]
    password: ENC[AES256_GCM,data:mc8Tq+9BFYV9w2xoUH4=,iv:x0eEV9Qb6YyzpUgNVFb4bdzcfIw8l473qk0+qe2sb18=,tag:FHowrfbjKngb7q94NZ8alw==,type:str]
sops:
    age:
        - recipient: age1dkfh6wr9gv8nd74fz6vjz9dj48ygcj2gtlvgjuwdzu8sz99q7deqan20me
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSnRGSmh1RzRkZDY1dUxw
            cWcrSWgzLzhMUCtDeWJkTGVXZTkxS3I3VzFzCnZWTXFZMGhiYzNURU45TWlNUHQ0
            S05tOXl0dEc5aS9KQ2RobTR1Mld4eUkKLS0tIGxCZngxbFV2MTNFZlJsYnc3dE9S
            NlpmSjhPTHd3RjRuYUp3RFppdGk1NHcKva8D5DD/qsZh454ix9lT2lMdKYGM/TW0
            4/0d1CQpljdm7We3oYqkYQKcYAF/1djxcQpw95QSKO7nRSSCQyydKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T09:36:04Z"
    mac: ENC[AES256_GCM,data:K/Tf2W4em4e/l5a/dnTCanVWEAn+Qk1y/Q1fXIGsyuzdx1pvBvdhAJg2/dfvNZmfiekqVExYZrKwLM1mKMEbtVOhrUSD/MKbYpV9Rz1EZvay2CTfp4TFEpJtziFN+W13MbRdAGwykRLUp9gIEL0NJK9GbfCQlyb1Wuxt7/JfjqE=,iv:AS2invjaqDtGLRblt07opK0hoRUNKiV3svVDoKKleKI=,tag:3B/Sv5iAF9RAMl58uMLVYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
