apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd

spec:
  template:
    spec:
      volumes:
        - name: custom-tools
          emptyDir: {}

        - name: sops-age
          secret:
            secretName: sops-age

      initContainers:
        - name: install-ksops
          image: alpine:3.20
          command: ["/bin/sh", "-c"]
          args:
            - |
              wget -O /custom-tools/ksops \
              https://github.com/viaduct-ai/kustomize-sops/releases/download/v4.4.0/ksops_Linux_x86_64 &&
              chmod +x /custom-tools/ksops
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools

        - name: install-kustomize
          image: alpine:3.20
          command: ["/bin/sh", "-c"]
          args:
            - |
              wget -O /tmp/kustomize.tar.gz \
              https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.2/kustomize_v5.4.2_linux_amd64.tar.gz &&
              tar -xzf /tmp/kustomize.tar.gz -C /custom-tools &&
              chmod +x /custom-tools/kustomize
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools

      containers:
        - name: argocd-repo-server

          volumeMounts:
            - name: custom-tools
              mountPath: /usr/local/bin/ksops
              subPath: ksops

            - name: custom-tools
              mountPath: /usr/local/bin/kustomize
              subPath: kustomize

            - name: sops-age
              mountPath: /home/argocd/.config/sops/age

          env:
            - name: XDG_CONFIG_HOME
              value: /home/argocd/.config
