apiVersion: ENC[AES256_GCM,data:u0Q=,iv:G29mNmcxQHXledMJ9wY3PwCcRIBV/glKH0dxVuYPQqc=,tag:CAst+558UFrC12XnAzrpzQ==,type:str]
kind: ENC[AES256_GCM,data:sSAIOhwe,iv:NEtmAJsMXj3Mu9pLTyXBod+iyrRekjkXiKI37g43h8s=,tag:Yj2FXeLdwXGQFXnfUrsN0w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:am08JXgnZUhH,iv:vC50MdrbdVhxmOKXQsioxg7Ennn/fVzrHZBZOgLmN28=,tag:cHP9fchRFkUDPKXbJtKv1w==,type:str]
    namespace: ENC[AES256_GCM,data:H6dRyeOHrw==,iv:fVrCnEPklURmnX6F7nglMpjZf+D3Gwvg9Pbi6ETTuPA=,tag:dWvUmTtjHLegPwjEgw7fqw==,type:str]
type: ENC[AES256_GCM,data:loeNZoyC,iv:Q0oxnVXyAusdHJv9aTZSaIBguvBY3GnpGdSTjLEnNU4=,tag:6vnQU43irLliEpoFaF0mVg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:WqPsTN8=,iv:zyTRJP58NpCdmQfWxwWLlOceWxWxG48YHbEVLhGC558=,tag:pP8fufkk44Lybcuc4NEgww==,type:str]
    password: ENC[AES256_GCM,data:B0W28LYzXfmUeGXtAD8=,iv:ejjGAOBYOVaM/xv2oDamP+h+qXDUSsGGo+0Z6SSm88c=,tag:DmmHwlFA57AG7taKd3eHLQ==,type:str]
sops:
    age:
        - recipient: age1dkfh6wr9gv8nd74fz6vjz9dj48ygcj2gtlvgjuwdzu8sz99q7deqan20me
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OUo2aU9iRGpHNUlzTy9B
            OXlSUnNsV2ZpVzZmQ2ZsQ3pCQ1MwQ2U0aEZrCldkYjNkTUV5V1VBMnBPZVdsWUFj
            OWZWQXpxNW9ySWpaaEg3RjRjbjFmUUUKLS0tIE53SjlCOHQxc0VUcUs2UGZ1OFRO
            bFNQREJ3bVYvTTN4TGxoaUhEdnJ1VW8KxDzYlRqKnQRL7QfUdQk0yItR47GxL+OJ
            c0bezCfCrA1v08hZlRJ1Tm+8wqhPk9auOzbkt1S4HuZG3s3MNaF7Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T13:33:30Z"
    mac: ENC[AES256_GCM,data:1CT/kMdnJRGEVl2GxuWRRwXVZqZ3exB71M3VAX6g0n+MuElY5YJoeYNIUHKRsdZWQxV2gRA8DII0rIZXSVtYS/Gw4ifICwoSMa3Ish64lCixQb9jC5Q7rhxZeXlbEMOkxVnDmZ51V05j8zS6YZ0fa/zLlTMbKV1Wqo1O886bzv8=,iv:AEg+NB4UoIuaRzHxjTPbZ3pgzZUjG6JeHC+QslEg4qk=,tag:FRpiQBCd7pqGUcGIV2Ac3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
