apiVersion: ENC[AES256_GCM,data:KMA=,iv:F/fZoaLbtABbZQUdwcgWku/+H7JHNJolaWFpkdxqOy4=,tag:ArQH5y/fdkWrtrCbzAjFQQ==,type:str]
kind: ENC[AES256_GCM,data:d7PYh+8F,iv:WfIH2ZkZkwwPE+ZQfzFDs9xVatkPBbHmTTHN+brqA5o=,tag:zYeH0riR3rPve3qasLP5pg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:inB4AzUDThhN,iv:S6i1wFg8FvBXwhxnuFAa2rRI9XDLh2WA1AKjupt61HE=,tag:B6+JHehQ8tz207qErA+sAw==,type:str]
type: ENC[AES256_GCM,data:wpHoNaAc,iv:SSKDLOFAWPd0AQGWyCcheThDS4ChmE83Xit3ORNQBvw=,tag:DdEh3Ghq1wNJW8fqLOKBiw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:bsFKedw=,iv:wzm5465Io5SoWUZ9KjwZyfpQ1vm9+UFU8ShW4INF3s0=,tag:gsmtQTGkOtP/2pWfD5H24Q==,type:str]
    password: ENC[AES256_GCM,data:Vls1aQj0zdCQ7EW14As=,iv:oiUXZOLh3JHBW2qlRYksWl0mUSGNLwE01APsLmbu9Vg=,tag:gXCMQmyp5ii7Wea4zuz1Tw==,type:str]
sops:
    age:
        - recipient: age1dkfh6wr9gv8nd74fz6vjz9dj48ygcj2gtlvgjuwdzu8sz99q7deqan20me
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaW9GUHFBZWtTa2tyYnI1
            aW5ZeG5sd3g5NWp1K2hCNmVRRjlqZmF4NGljCm9SSERsaXZYU0tDOEl5R3JQc01M
            TmR0SGtoTll0eW0rTVkrRk8vU1N5RTAKLS0tIFVTR1lnMWdna3pzVmh2V2hPdVMy
            c1R1U1RvZUo1MWQ5ajdmZURRREJMbkUKoWfZXwEOIbgqRF+06LrC53iBDjwKySLX
            8vmpdaphEJUyZy6OadkEVl16lmcgFidY63kSsVvR+SRwUnaE4iDT5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T13:30:58Z"
    mac: ENC[AES256_GCM,data:7vUHypquvDj8IFs3ZXBR7Wc/kNBCktrz+aKBx2zdjRGCFlmjda+B4tBDUJ1vx68a9NMEixmQbzhqMt/mNOI7aYb1tq9wo/J1G2hxe6UTDLOmjsjcl2c6a5J4d0LluBrTOjt4Ad3aO5oeL2vNSmbPKlK6Q0sB8A6pOHs0j2esGQI=,iv:FdMJChtCqIhxR5YcH1+/5htaBdARf39XjeYFdLHVlco=,tag:GKxsEpuP5R3IwpD0oi8e3g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
