apiVersion: ENC[AES256_GCM,data:jJo=,iv:u3S/pVrQe7HMwk6JWAAAXkVNaw7ejiXFZk0CUHYo3UM=,tag:0sSgdHsJ9uVlYAOw4TvcAw==,type:str]
kind: ENC[AES256_GCM,data:6X9RYDOh,iv:VS4/xO/Bpb4YDiAq6YylqRuKAUWGGPw81EqBSdoJzxk=,tag:uwigL+UvL1oRhXKeaxrdSw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lCPWUrBUWZ/H,iv:K22NxqPuHygAE2bsrmMi9Lx5aMEgbVGxA/8mUTMbwwk=,tag:MA8vaKZ82xaEZP7wiZgr+A==,type:str]
    namespace: ENC[AES256_GCM,data:CW0qpTGmfA==,iv:czmfyq089a5mYVPK+pVH9hWDVSaWlT9/7lIRmiHqlnU=,tag:w5xeXka7LNl41bsdhKOqFA==,type:str]
type: ENC[AES256_GCM,data:HuOLXUvi,iv:JjKd+QuyLAFj1FHj32+Gx+rV9iVDf5YqeSZ3R44F2DQ=,tag:oLY4Afu2jSaR3lPDggZUdg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:i4BfiDU=,iv:fwnXtZgWer7xT5OQa3Y97TO0bNnIe3lX9wgci55CSG0=,tag:cMsYCCXkIftJtZHral4Yow==,type:str]
    password: ENC[AES256_GCM,data:fsK0e1czljaWJ7RGedjLjphM13IM,iv:YOpGsvhc+GYhtm634fx2iNswud5ADxL1pPczOB0sFEg=,tag:GpQe8ZdMMKl0bJXpImVcJQ==,type:str]
sops:
    age:
        - recipient: age1e2p37unrnd3zddckf2ujkeff7drmhn9jt9vffwa4kn575qr88fcsfglm6f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQ0E3eXZlaTYzTmZNMkZv
            cDlYZ3VnTVB3RXl2TjAyc2tRYzFDQXNXMHlRCm5tMWZGZDlFTWpxdmovWjIxdDY4
            SUd3VU5Eb0kyUEoza0lLYVZCMWY4VU0KLS0tIFh2VnhRUmpyekNHbnJCNG1ZNXNS
            cnZ4LzIwQ1IwYzNML2dMYTVKQUgxK2MKdC6H8OeAjfEMXFZV27MvbcfuDG9CUcVk
            8GwhCYBuM28Ve70gUilGKo+1W6x2J7/q2CQr/fCO14nmKLvmFTlbTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T11:23:48Z"
    mac: ENC[AES256_GCM,data:WGxGzcYqLQYyKq0TVZPENtfrQdu4ep91BVT7rrxRjlZqajQ+bFBjWmOcGan6lWgx7aMuUL+bwNFxYA1dFI001Eq5FaoCvjYIwsdjzieRiXQvyKl/D44l09zJV+1GmWKtlR/Ex81gmXB/4zikAG7gjSABXV/LheiXuddL2OvY5+c=,iv:+L5mpt8vQXgimuvLQdujh4zT+ysfh48KuUNz9O/WDZE=,tag:tVZS4gB78n62CkaZ8WxrYw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
